import { join } from "node:path";
import { writeFileSafe } from "../utils/file-system.js";
import type { GeneratorResult, PackageManagerInfo } from "../types/config.js";

/**
 * Generate Quick Reference guide for developers
 */
export async function generateQuickReference(
  targetDir: string,
  pm: PackageManagerInfo
): Promise<GeneratorResult> {
  const result: GeneratorResult = {
    created: [],
    modified: [],
    skipped: [],
    backedUp: [],
  };

  const quickRefPath = join(targetDir, ".github", "QUICK_REFERENCE.md");

  const content = `# RaftStack Quick Reference

> One-page guide for the RaftStack Git workflow

## 🚀 Daily Workflow

### 1. Create a Branch

\`\`\`bash
# Format: <type>/<short-description>
git checkout -b feature/user-authentication
git checkout -b bugfix/login-redirect
git checkout -b hotfix/payment-timeout
\`\`\`

**Branch types:** \`feature\`, \`bugfix\`, \`hotfix\`, \`chore\`, \`refactor\`

### 2. Make Commits

\`\`\`bash
# Use the interactive commit tool
${pm.run} commit
\`\`\`

This will prompt you for:
- Type (feat, fix, docs, etc.)
- Scope (optional)
- Description
- Body (optional)
- **Task link (required)**

### 3. Commit Message Format

\`\`\`
✨ feat(auth): add user login form

- Created LoginForm component
- Added form validation
- Integrated with API

Task: https://app.asana.com/0/project/task
\`\`\`

### 4. Create Pull Request

\`\`\`bash
git push -u origin feature/my-feature
# Then create PR on GitHub
\`\`\`

---

## 📝 Commit Types

| Type | Emoji | Use For |
|------|-------|---------|
| feat | ✨ | New feature |
| fix | 🐛 | Bug fix |
| docs | 📝 | Documentation |
| style | 💄 | Formatting (no logic change) |
| refactor | ♻️ | Code restructuring |
| perf | ⚡ | Performance improvement |
| test | ✅ | Adding tests |
| build | 📦 | Build system changes |
| ci | 👷 | CI configuration |
| chore | 🔧 | Maintenance |

---

## ✅ PR Checklist

Before submitting:
- [ ] Branch name follows convention
- [ ] All commits have task links
- [ ] Tests pass locally
- [ ] PR description filled out
- [ ] Size is reasonable (< 400 lines)

---

## 🔧 Useful Commands

\`\`\`bash
# Interactive commit
${pm.run} commit

# Check compliance metrics
${pm.exec} @raftlabs/raftstack metrics

# Run linting
${pm.run} lint

# Run tests
${pm.run} test
\`\`\`

---

## ❌ Common Mistakes

| Wrong | Right |
|-------|-------|
| \`Feature/UserAuth\` | \`feature/user-auth\` |
| \`fixed bug\` | \`fix(auth): resolve login redirect\` |
| No task link | Always include \`Task: <url>\` |
| 1000+ line PR | Split into smaller PRs |

---

## 📚 More Info

- [CONTRIBUTING.md](../CONTRIBUTING.md) - Full contribution guide
- [RaftStack Docs](https://github.com/Raft-Labs/raftstack) - CLI documentation

---

*Generated by RaftStack - Git workflow standardization for teams*
`;

  const writeResult = await writeFileSafe(quickRefPath, content);

  if (writeResult.created) {
    if (writeResult.backedUp) {
      result.modified.push(".github/QUICK_REFERENCE.md");
      result.backedUp.push(".github/QUICK_REFERENCE.md");
    } else {
      result.created.push(".github/QUICK_REFERENCE.md");
    }
  } else {
    result.skipped.push(".github/QUICK_REFERENCE.md");
  }

  return result;
}
